name: Setup nektos/act
description: Sets up the nektos/act cli tool
branding:
  icon: 'play'
  color: 'blue'
inputs:
  default-runner-size:
    description: default runner size for act
    required: false
    default: medium

runs:
  using: "composite"
  steps:
    - name: Install nektos/act
      shell: bash
      run: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      
    - name: Add nektos/act to path
      shell: bash
      run: |
        sudo mkdir /opt/hostedtoolcache/act
        sudo mv ./bin /opt/hostedtoolcache/act/
        echo "/opt/hostedtoolcache/act/bin/" >> $GITHUB_PATH

    - name: Setup Act - Large image
      if: inputs.default-runner-size == 'large'
      shell: bash
      run: |
        echo "-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:full-latest" > ~/.actrc
        echo "-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:full-20.04" >> ~/.actrc
        echo "-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:full-18.04" >> ~/.actrc

    - name: Setup Act - Medium image
      if: inputs.default-runner-size == 'medium'
      shell: bash
      run: |
        echo "-P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest" > ~/.actrc
        echo "-P ubuntu-20.04=ghcr.io/catthehacker/ubuntu:act-20.04" >> ~/.actrc
        echo "-P ubuntu-18.04=ghcr.io/catthehacker/ubuntu:act-18.04" >> ~/.actrc
        echo "-P ubuntu-22.04=ghcr.io/catthehacker/ubuntu:act-22.04" >> ~/.actrc

    - name: Setup Act - Micro image
      if: inputs.default-runner-size == 'micro'
      shell: bash
      run: |
        echo "-P ubuntu-latest=node:16-buster-slim" > ~/.actrc
        echo "-P ubuntu-20.04=node:16-buster-slim" >> ~/.actrc
        echo "-P ubuntu-18.04=node:16-buster-slim" >> ~/.actrc
        echo "-P ubuntu-22.04=node:16-bullseye-slim" >> ~/.actrc

    - name: Incorrect default runner size
      if: (inputs.default-runner-size != 'micro') && (inputs.default-runner-size != 'medium') && (inputs.default-runner-size != 'large')
      shell: bash
      run: |
        echo "Incorrect default-runner-size"
        exit 1
