name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "action.yml"
  workflow_dispatch:
  pull_request:
    paths:
      - "action.yml"

jobs:
  tests:
    strategy:
      matrix:
        default-runner-size: [micro, medium, large]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup act cli
        uses: ./
        with:
          default-runner-size: ${{ matrix.default-runner-size }}

      - name: Run act
        run: act -l
