name: Tests

on:
  push:
    branches:
      - main
    paths:
      - "action.yml"
  workflow_dispatch:
  pull_request:
    paths:
      - "action.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup act cli
        uses: ./
        with:
          default-runner-size: medium

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - run: npm i

      - run: npm test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
